name: kandy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  url_launcher: ^5.4.2
  flutter_vlc_player: ^2.0.0
  carousel_slider:
  bottom_navy_bar: ^5.4.0
  expandable_card: ^0.0.3+1
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  dio: ^1.0.13
  folding_cell: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/Netflix-logo.png
    - images/netflix_icon.png
    - images/launch_image.png
